import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Header from '../components/Header'
import Hero from '../components/Hero'
import CatsInSpace from '../components/CatsInSpace'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>D Atas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CatsInSpace />
      {/* <Header /> */}
      <Hero />
      {/* <Footer /> */}
    </>
  )
}
