import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {
  createTheme,
  responsiveFontSizes,
  ThemeProvider,
} from '@mui/material/styles'

import Hero from '../components/Hero'

let theme = createTheme()
theme = responsiveFontSizes(theme)

export default function Home() {
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>D Atas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </ThemeProvider>
  )
}
